on:
  schedule:
    - cron: '53 20,8 * * *'
  workflow-dispatch:
  


jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python update_config.py
      - run: python update_game.py
      - run: rm -rf data/excel/
      - run: mkdir -p tmp/
      - uses: actions/checkout@v3
        with:
          repository: Kengxxiao/ArknightsGameData
          path: tmp/
          sparse-checkout: zh_CN/gamedata/excel/
      - run: mv tmp/zh_CN/gamedata/excel/ data/
      - run: rm -rf tmp/
      - run: python update_activity.py
      - run: git config --global user.name 'AKRobot'
      - run: git config --global user.email 'akrobot[bot]@users.noreply.github.com'
      - run: git add . && git commit -m 'Automatic update' && git push origin master || true
